### ISSUE TITLE
SKi Recipe Conflicts Boat Recipe

### ISSUE THREAD

**Issue by FriendlyGamer** [qawsedrftgzh/Ski#1]
On the Sfinv included Recipe Guide it says that you need five planks as you were making a boat. But you can't have the same recipe as the boat. 

Could you please fix this so it works right on my server? 

Thanks very much in advance!

**Comment by qawsedrftgzh** [comment]
Thanks for using it on a server. 😄 It will be ready today or tomorrow.

**Comment by qawsedrftgzh** [comment]
It is fixed. README will be updated, in a few hours

**Comment by qawsedrftgzh** [comment]
README is fixed.

**Comment by FriendlyGamer** [comment]
> Thanks for using it on a server.  It will be ready today or tomorrow.

You are very welcome! I was trying to find something to add to the immersive factor of the server as explained on my "deafblindminetestgaming.com" website. Seeing as there were lacking in existing mods that I use for snow travel so thanks for making and fixing this mod. :)
> It is fixed. README will be updated, in a few hours

Awesome thank you for the quick fix also! :)

> README is fixed.

Awesome thanks as well.
